### ISSUE TITLE
该插件会跳过所有副本的过场动画

### ISSUE THREAD

**Issue by svr2kos2** [svr2kos2/FFXIV_ACT_CutsceneSkip#1]
该插件会跳过所有副本的过场动画
后续会改为只跳过动画城和冬瓜煲

**Comment by zkj2716491** [comment]
act安装dll插件以后显示Working：D

**Comment by AmazeFPig** [comment]
请问这个插件要怎么用啊，ACT导入只能导入dll和exe

**Comment by svr2kos2** [comment]
> 

[在Release页面下载](https://github.com/svr2kos2/FFXIV_ACT_CutsceneSkip/releases/download/release/FFXIV_ACT_CutsceneSkip.dll)

**Comment by svr2kos2** [comment]
[只在冬瓜煲和动画城跳过动画](https://github.com/svr2kos2/FFXIV_ACT_CutsceneSkip/commit/aec65f545e3c912cec7e31b3eff34e9b2e0902d2)
